# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'DragDropDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DragDropDemo

  pod 'IQKeyboardManager'
  pod 'SkyFloatingLabelTextField'
  pod 'ReachabilitySwift'
  pod "KRProgressHUD"

end
